#!/bin/bash
#PBS -N NSQ2K_201_S2
#PBS -l nodes=2:ppn=2:gpus=2
#PBS -l walltime=04:00:00
#PBS -l mem=64gb


#setting paths tostore singularity/conda files

export APPTAINER_TMPDIR=/user/gent/446/vsc44685/ScratchVO_dir/apptainer_cache/tmp
export APPTAINER_CACHEDIR=/user/gent/446/vsc44685/ScratchVO_dir/singularity
export SINGULARITY_CACHEDIR=/user/gent/446/vsc44685/ScratchVO_dir/singularity
export NXF_SINGULARITY_CACHEDIR=/user/gent/446/vsc44685/ScratchVO_dir/apptainer_cache
export CONDA_PKGS_DIRS=/user/gent/446/vsc44685/ScratchVO_dir/conda_pkgs
export NXF_CONDA_CACHEDIR=/user/gent/446/vsc44685/ScratchVO_dir/conda_cache
conda activate /user/gent/446/vsc44685/DataVO_dir/miniconda2/envs/nf-core

#go to work directoty
cd /user/gent/446/vsc44685/ScratchVO_dir/panoramaseq/personal/ 

#load nextflow module
ml Nextflow/25.04.4

nextflow run main.nf -profile singularity --input ./assets/samplesheet.csv --outdir /user/gent/446/vsc44685/ScratchVO_dir/test_nf_core_local
